import = ["~/.config/alacritty/themes/everforest_dark.toml"]

[cursor.style]
blinking = "Always"
shape = "Block"

[font]
size = 13.0

[font.normal]
family = "Red Hat Mono"
style = "SemiBold"

[window]
padding = { x = 15, y = 0 }
dynamic_padding = true
dynamic_title = true
opacity = 0.95

[window.dimensions]
columns = 132
lines = 24

[selection]
save_to_clipboard = true
