format = "$all"

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"

[cmd_duration]
min_time = 500
show_milliseconds = true

[package]
symbol = "pkg "
disabled = true

[kubernetes]
symbol = "k8s "
detect_folders = ['.kube']
disabled = false

[username]
show_always = true

[time]
format = "[$time]($style) "
time_format = "%R"
disabled = false

[helm]
symbol = "helm "

[git_commit]
tag_symbol = " tag "

[git_status]
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"

[cmake]
symbol = "cmake "

[dotnet]
symbol = ".NET "

[docker_context]
symbol = "docker "

[git_branch]
symbol = "git "

[golang]
symbol = "go "

[guix_shell]
symbol = "guix "

[hg_branch]
symbol = "hg "

[java]
symbol = "java "

[memory_usage]
symbol = "memory "

[perl]
symbol = "pl "

[python]
symbol = "py "

[rust]
symbol = "rs "

[nodejs]
symbol = "nodejs "

[buf]
symbol = "buf "

[sudo]
symbol = "sudo "

[terraform]
symbol = "terraform "

[aws]
symbol = "aws "

[azure]
symbol = "az "

[battery]
discharging_symbol = "batt "

[os]
disabled = true

[os.symbols]
Alpaquita = "alq "
Alpine = "alp "
Amazon = "amz "
Android = "andr "
Arch = "rch "
Artix = "atx "
CentOS = "cent "
Debian = "deb "
DragonFly = "dfbsd "
Emscripten = "emsc "
EndeavourOS = "ndev "
Fedora = "fed "
FreeBSD = "fbsd "
Garuda = "garu "
Gentoo = "gent "
HardenedBSD = "hbsd "
Illumos = "lum "
Linux = "lnx "
Mabox = "mbox "
Macos = "mac "
Manjaro = "mjo "
Mariner = "mrn "
MidnightBSD = "mid "
Mint = "mint "
NetBSD = "nbsd "
NixOS = "nix "
OpenBSD = "obsd "
OpenCloudOS = "ocos "
openEuler = "oeul "
openSUSE = "osuse "
OracleLinux = "orac "
Pop = "pop "
Raspbian = "rasp "
Redhat = "rhl "
RedHatEnterprise = "rhel "
Redox = "redox "
Solus = "sol "
SUSE = "suse "
Ubuntu = "ubnt "
Unknown = "unk "
Windows = "win "
