# Colors (Everforest Dark)

[terminal.shell]
program = "tmux"

# Default colors
[colors.primary]
background = '#2d353b'
foreground = '#d3c6aa'

# Normal colors
[colors.normal]
black   = '#475258'
red     = '#e67e80'
green   = '#a7c080'
yellow  = '#dbbc7f'
blue    = '#7fbbb3'
magenta = '#d699b6'
cyan    = '#83c092'
white   = '#d3c6aa'

# Bright colors
[colors.bright]
black   = '#475258'
red     = '#e67e80'
green   = '#a7c080'
yellow  = '#dbbc7f'
blue    = '#7fbbb3'
magenta = '#d699b6'
cyan    = '#83c092'
white   = '#d3c6aa'

[cursor.style]
blinking = "Always"
shape = "Block"

[font]
size = 13.0

[font.normal]
family = "Cascadia Mono"
style = "SemiBold"

[window]
padding = { x = 15, y = 0 }
dynamic_padding = true
dynamic_title = true
opacity = 0.95
startup_mode = "Maximized"

[selection]
save_to_clipboard = true
